### ISSUE TITLE
Correct word in result dialogue remains same 

### ISSUE THREAD

**Issue by mukeshwebs** [ernestaskaz/Zodziu_zaidimas#1]
Hey bro, I have noticed a bug in your app when we play games multiple times the Correct word is: "text" the text part remains the same in each trial of the game fix it to make a good one.

**Comment by ernestaskaz** [comment]
Thanks.

**Comment by mukeshwebs** [comment]
Bro When are planning the update for this bug ? I can contribute to your project to implement multiplayer features.

**Comment by ernestaskaz** [comment]
Hey, the bug is fixed, Correct word updates on s10 and AVDs.

No need for contributors, thanks.

Regards,
