### ISSUE TITLE
one more bug

### ISSUE THREAD

**Issue by mukeshwebs** [ernestaskaz/Zodziu_zaidimas#2]
after play again the game doesn't turn each incorrect words grey in the keyboard.

**Comment by mukeshwebs** [comment]
![image](https://user-images.githubusercontent.com/53649320/156972329-085c46fd-84f8-4591-a054-07c8a0096ac4.png)

**Comment by mukeshwebs** [comment]
Probably the incorrect part of the code is here you are not using any condition for grey blocks..

viewmodel>mainActivity

![image](https://user-images.githubusercontent.com/53649320/157007760-789c3437-75ff-4c16-8876-8071c233e9be.png)

**Comment by ernestaskaz** [comment]
it does on my end.

Regards,
