### ISSUE TITLE
sync issue

### ISSUE THREAD

**Issue by wangwpapril** [ernestaskaz/Zodziu_zaidimas#4]
nothing changed, getting below issue when sync on Android Studio:
Could not resolve all files for configuration ':app:androidApis'.
Failed to transform android.jar to match attributes {artifactType=android-mockable-jar, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime, returnDefaultValues=false}.
Execution failed for MockableJarTransform: /Users/willwang/Library/Android/sdk/platforms/android-32/android.jar.
Cannot create mockable android.jar
/Users/willwang/Library/Android/sdk/platforms/android-32/android.jar

**Comment by mukeshwebs** [comment]
load from local storage

**Comment by wangwpapril** [comment]
sorry I am not quite understand: how can I load it from local storage? its not in the folder : Android/sdk/platforms/android-32/android.jar, and I don't know how to download it.

**Comment by mukeshwebs** [comment]
are on any social network where we can connect, Twitter ?

**Comment by wangwpapril** [comment]
Thank you, I have figured it out.

**Comment by mukeshwebs** [comment]
now are u able to build project properly?
