### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mukeshwebs** [ernestaskaz/Zodziu_zaidimas#5]
When we play game again The first letter in each line is not properly highlighted in the keyboard below the grid.  delete key deletes the whole word in that line if it deletes only single it  Much easier to fix a miss typed letter.

**Comment by ernestaskaz** [comment]
is properly highlighted on my end. Check api level. minimum should be 31.

deletion of whole line is a feature. Project is won't be updated anymore on github.
